language: java
jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "AeS/ZMWYKD8VghMN/Lt3918ECelRSsifT7IgVaWrWQJmhKbXjLk7PW0Y9VxwjAq/4MSVf1aPu4ee56OliwV79SU7YjrV7jcYKBu5GDnXfzTF6Forw+QrPm2VEpOdP6MqPVUKxr7OLu//P+gERGO9eV595tPT/KeHrgls7WUJQVE="

addons:
  coverity_scan:
    project:
      name: "kshchepanovskyi/protostuff-compiler"
      description: "Build submitted via Travis CI"
    notification_email: schepanovsky@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master
